/**
 * Error codes shared with the backend (app/Enums/ErrorCode.php).
 * Keep in sync when new codes are added.
 */
export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED',

  // Authorization
  AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
  AUTHZ_MISSING_PERMISSION = 'AUTHZ_MISSING_PERMISSION',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',

  // Business Logic
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  VEHICLE_ALREADY_SOLD = 'VEHICLE_ALREADY_SOLD',
  STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT',

  // External
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  VIN_DECODE_FAILED = 'VIN_DECODE_FAILED',

  // Server
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_MAINTENANCE = 'SERVER_MAINTENANCE',
}

export enum ErrorCategory {
  NETWORK = 'NETWORK',
  AUTH = 'AUTH',
  VALIDATION = 'VALIDATION',
  PERMISSION = 'PERMISSION',
  NOT_FOUND = 'NOT_FOUND',
  BUSINESS = 'BUSINESS',
  SERVER = 'SERVER',
}
